
host_list = [
  {
    :name => "host1",
    :box => "centos/7",
    :box_url => "https://mirrors.ustc.edu.cn/centos-cloud/centos/7/vagrant/x86_64/images/CentOS-7.box"
  },
  {
    :name => "host2",
    :box => "centos/7",
    :box_url => "https://mirrors.ustc.edu.cn/centos-cloud/centos/7/vagrant/x86_64/images/CentOS-7.box"
  },
  {
    :name => "host3",
    :box => "centos/7",
    :box_url => "https://mirrors.ustc.edu.cn/centos-cloud/centos/7/vagrant/x86_64/images/CentOS-7.box"
  }
]

Vagrant.configure("2") do |config|

  ##
  ## 全局的配置
  ##

  # 使用公共的ssh 私钥
  config.ssh.insert_key = false

  # 定义两台机器
  host_list.each do |item| 
    config.vm.define item[:name] do |host|
      host.vm.hostname = item[:name]
      host.vm.box = item[:box]
      host.vm.box_url = item[:box_url]
    end 
  end 
end
